### ISSUE TITLE
修改返回文本预设导致插件失效

### ISSUE THREAD

**Issue by Readedd** [SummonHIM/koishi-plugin-bili-parser#1]

**Comment by SummonHIM** [comment]
请问是解决了吗

**Comment by Readedd** [comment]
> 请问是解决了吗

再次重启尝试发送链接解析，ssh返回
 at async type_parser (/root/koshibot/koishi-app/node_modules/@summonhim/koishi-plugin-bili-parser/lib/link_parse.js:174:36)

**Comment by SummonHIM** [comment]
> > 请问是解决了吗
> 
> 再次重启尝试发送链接解析，ssh返回 at async type_parser (/root/koshibot/koishi-app/node_modules/@summonhim/koishi-plugin-bili-parser/lib/link_parse.js:174:36)

请发送详细日志
